title: Pack Docs
description: Documentation for content pack development in CherryGrove.
theme: just-the-docs
color_scheme: dark

url: https://docs.cherrygrove.dev

aux_links:
  CherryGrove's Official Website: https://cherrygrove.dev
