title: CherryGrove Packs
description: Documentation for content pack development in CherryGrove.
theme: just-the-docs

url: https://docs.cherrygrove.dev

aux_links:
  Official Website: https://cherrygrove.dev
